<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sale_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1becabd1-c5e3-4a4d-9e5a-b741f0fd23bd</testSuiteGuid>
   <testCaseLink>
      <guid>e226aa7d-f389-4cd7-b446-00aa0f35b864</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_ECommerce_No_AdditionalPrompting</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82316b92-83d7-4370-8daf-be9f58a1a3ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce098a49-facf-4830-b258-926d803b1d03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f1912ba-c91e-4198-87aa-f70e91c01c69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7215d7e2-9bc7-484a-bc13-97682fe3e599</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dac3a32-3e05-4af2-9bb2-e50478086a19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7973372-3774-4325-b936-d1ddb3429063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a03edab-fea5-42d2-b21e-a04001f02900</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb32f45-0bfb-4515-9fbe-95fb7f9cd311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d55279d4-3e9a-4bbb-966a-8f0eaae8f7fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_Moto_No_AdditionalPrompting</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d95c7e-4cc1-4775-8dea-5d8281aaa40a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>595eb94a-ae22-4e18-8268-d5cdc2439cb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>540f1fa8-eb57-42e2-8b74-a8d657eaa776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f564a47-4fb7-47ae-8fc3-29277f36a983</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e88cf46-a110-43d5-ab6c-3a079494eba0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5b3cffa-e937-49d8-850e-25f782b8b92f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20d86093-d36b-410a-94dc-dbf18aba3124</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_Retail_No_AdditionalPrompting</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4cd89d7-44db-4f5e-b9a1-ea824144e869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19f3cd86-c171-4182-92de-1189c115e4e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e038ab76-1773-4c27-9bd4-b36e10c54626</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a338cfa9-97cc-4cb0-b2c2-691d009a8261</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>829762c5-6345-45d0-a2fc-defa850e9fe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc6e3761-74e5-4139-901b-ae2e259a7e45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cecd97ee-d2ac-4c1c-9703-78e8ba2e466a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afd6895c-5029-4bdd-8503-34812611a1b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d747eb0e-4ab0-4b52-9a27-279883d57859</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa9d6050-f257-4df0-83bf-b30d87fef63c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_Retail_RecurringPayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ad6117b-38ed-450e-b97d-3e5f6821c9d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be5f5af6-a4d4-4151-9a2c-7ac95e1ce94e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0948849c-1b53-4b0b-8568-a4f54b63c0d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e49f43ad-40b0-47c1-bdfa-97af79012782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6faa2a90-c109-4418-acb8-eabf80c5836d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6dbd50d-f6ef-4eee-b903-27bf09dbe94d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7d839f4-d393-4b72-b897-0f5008ffebb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afd6b0f0-bf25-40d1-b331-b460a42f0a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>978b72ba-f45c-4b1c-ab6e-2b9e550f8784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3f8bc28-b373-4977-a5e1-8283cc494782</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d84ddc1-aff6-4756-b63b-dcbad7d88592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_Retail_SaveToVault</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8f7d4f8-98f2-4365-9515-ae355f040894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3921ad-0125-421d-93ee-347d41db8e1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0088e7e5-2f53-4864-a301-131eb3cf856d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92804667-8159-46c4-accb-953b5cf886dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f31dbe1-1205-4e5a-a186-001ebb60dcd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e377c22-634d-47ba-8037-309f3513f60e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c4c6bc-541b-4697-8a8c-5c04329bf3d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f894942-e7ac-439e-853c-11feffed404c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e87b546-6425-4dfa-a3fe-4efd3cb667d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/VPOS_Sale_Transaction_Retail_SetAsFuturePayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ad6117b-38ed-450e-b97d-3e5f6821c9d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be5f5af6-a4d4-4151-9a2c-7ac95e1ce94e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0948849c-1b53-4b0b-8568-a4f54b63c0d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e49f43ad-40b0-47c1-bdfa-97af79012782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6faa2a90-c109-4418-acb8-eabf80c5836d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6dbd50d-f6ef-4eee-b903-27bf09dbe94d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7d839f4-d393-4b72-b897-0f5008ffebb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afd6b0f0-bf25-40d1-b331-b460a42f0a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>978b72ba-f45c-4b1c-ab6e-2b9e550f8784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3f8bc28-b373-4977-a5e1-8283cc494782</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
